### ISSUE TITLE
Crashes when downloading on Linux (At unzipping)

### ISSUE THREAD

**Issue by Rajala1404** [Grasscutters/Cultivation#225]
If you start Cultivation as root (with sudo) it crashes after downloading the Resources when unzipping the downloaded Files.
Log with verbose Logging:
```
rajala1404@archlinux /d/h/r/Downloads [101]> sudo -E RUST_BACKTRACE=full cultivation

** (cultivation:12708): WARNING **: 00:04:13.924: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Could not determine the accessibility bus address
thread 'main' panicked at src/unzip.rs:27:38:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x570a74196f0c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x570a74196f0c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x570a74196f0c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x570a74196f0c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x570a741c8660 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x570a741c8660 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x570a7419222f - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x570a74196cf4 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x570a74196cf4 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x570a74198547 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x570a741982af - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x570a741989c8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x570a741988ae - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x570a741973d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x570a74198612 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x570a73630c85 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x570a73631163 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x570a738eac2a - cultivation::unzip::unzip::h2da20b3585e383bb
  18:     0x570a739234d0 - cultivation::main::{{closure}}::h5095b15d3c50b501
  19:     0x570a73913471 - tauri::window::Window<R>::on_message::h897d99db4ae352fc
  20:     0x570a7368daaa - tauri::manager::WindowManager<R>::prepare_ipc_handler::{{closure}}::hcd56b250dd3b3f4c
  21:     0x570a7363f335 - tauri_runtime_wry::create_ipc_handler::{{closure}}::h4d0832bc007a03cc
  22:     0x570a73920650 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h136df6e8e0bc6356
  23:     0x570a73fbf303 - <O as webkit2gtk::auto::user_content_manager::UserContentManagerExt>::connect_script_message_received::script_message_received_trampoline::h47d9bc152b803368
  24:     0x7d6b289b1730 - g_closure_invoke
  25:     0x7d6b289e0896 - <unknown>
  26:     0x7d6b289d17a2 - <unknown>
  27:     0x7d6b289d19d7 - g_signal_emit_valist
  28:     0x7d6b289d1a94 - g_signal_emit
  29:     0x7d6b2cab2ee4 - <unknown>
  30:     0x7d6b2c636b5f - <unknown>
  31:     0x7d6b2c63724c - <unknown>
  32:     0x7d6b2c963a35 - <unknown>
  33:     0x7d6b2ca0187d - <unknown>
  34:     0x7d6b2c958829 - <unknown>
  35:     0x7d6b2c95cb0a - <unknown>
  36:     0x7d6b2a91b44b - <unknown>
  37:     0x7d6b2a91b52d - <unknown>
  38:     0x7d6b288ad199 - <unknown>
  39:     0x7d6b2890c3bf - <unknown>
  40:     0x7d6b288ac712 - g_main_context_iteration
  41:     0x7d6b2afed3a7 - gtk_main_iteration_do
  42:     0x570a7405196d - gtk::auto::functions::main_iteration_do::h064df67baa469371
  43:     0x570a739096d8 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h9202063675317948
  44:     0x570a739fd988 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h0f5436774692c4a5
  45:     0x570a73656a7c - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hbafb95fc6594c883
  46:     0x570a7366e8ac - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::h58caa5840f2c2f7e
  47:     0x570a739118ff - tauri::app::Builder<R>::run::h29990daddf47edbf
  48:     0x570a738e9031 - cultivation::main::h573831dede15b0f8
  49:     0x570a739e23e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcce40fa67803ca89
  50:     0x570a739744b2 - std::rt::lang_start::{{closure}}::heb4bdbee8e4ccce4
  51:     0x570a7418bfa7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  52:     0x570a7418bfa7 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  53:     0x570a7418bfa7 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  54:     0x570a7418bfa7 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  55:     0x570a7418bfa7 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  56:     0x570a7418bfa7 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  57:     0x570a7418bfa7 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  58:     0x570a7418bfa7 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  59:     0x570a7418bfa7 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  60:     0x570a7397449e - std::rt::lang_start::hfc13c9487c14b999
  61:     0x7d6b27e43cd0 - <unknown>
  62:     0x7d6b27e43d8a - __libc_start_main
  63:     0x570a73631615 - _start
  64:                0x0 - <unknown>
```

**Comment by Rajala1404** [comment]
Solution:
I just compiled it by myself with the newest Git code and it worked
