### ISSUE TITLE
rust error in proxy

### ISSUE THREAD

**Issue by CurrentSubset68** [Grasscutters/Cultivation#226]
```
cultivation -p
Starting proxy server...
Connecting to proxy...
thread 'main' panicked at src/proxy.rs:294:34:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
sudo cultivation -p
Starting proxy server...
Connecting to proxy...
thread 'main' panicked at src/proxy.rs:294:34:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by NotThorny** [comment]
This is due to AAGL (anime_launcher_sdk) not being found, so the config for it is also not found, leading to an error unwrapping the config for it.
Make sure you have AAGL installed and set up.

**Comment by CurrentSubset68** [comment]
whoops forgot to close this
