### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by LengXudong** [Grasscutters/Cultivation#230]
Hello,

When I launch the game client, the server window displays the following message:
08:04:28 <ERROR:SceneScriptManager> [LUA] call trigger failed in group 133307094 with condition_EVENT_GROUP_LOAD_94006,ScriptArgs(param1=133307094, param2=0, param3=0, source_eid=0, target_eid=0, group_id=133307094, source=null, type=29)
org.luaj.vm2.LuaError: script:123 attempt to call nil
stack traceback:
        script:123: in function '__index'
        script:123: in function <script:121>
        [Java]: in ?
        at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
        at org.luaj.vm2.LuaValue.callmt(Unknown Source)
        at org.luaj.vm2.LuaValue.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:1004)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:997)
        at emu.grasscutter.scripts.SceneScriptManager.evaluateTriggerCondition(SceneScriptManager.java:933)
        at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:905)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:886)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$28(SceneScriptManager.java:857)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
08:04:28 <ERROR:SceneScriptManager> [LUA] call trigger failed in group 133307094 with condition_EVENT_GROUP_LOAD_94006,ScriptArgs(param1=133307094, param2=0, param3=0, source_eid=0, target_eid=0, group_id=133307094, source=null, type=29)
org.luaj.vm2.LuaError: script:123 attempt to call nil
stack traceback:
        script:123: in function <script:121>
        [Java]: in ?
        at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
        at org.luaj.vm2.LuaValue.callmt(Unknown Source)
        at org.luaj.vm2.LuaValue.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:1004)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:997)
        at emu.grasscutter.scripts.SceneScriptManager.evaluateTriggerCondition(SceneScriptManager.java:933)
        at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:905)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:886)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$28(SceneScriptManager.java:857)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403186.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403513.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402002.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403003.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316134.lua
08:04:31 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001112.lua
08:10:33 <WARN:SceneScriptManager> trying to cancel a timer that's not active 133003429 camera
08:10:33 <WARN:ScriptLib> [LUA] Call unimplemented BeginCameraSceneLook with {is_force_walk:false,look_pos:table: 12b9b2b6,duration:1,is_force:true,is_set_screen_XY:false,follow_pos:table: 3256bb03,is_change_play_mode:false,screen_x:0,is_allow_input:false,is_broadcast:false,is_set_follow_pos:false,screen_y:0,delay:0,is_recover_keep_current:true,}
08:11:45 <WARN:SceneScriptManager> failed to create entity with group 133003090 and config 472
08:13:10 <WARN:ScriptLib> [LUA] Call unimplemented MarkPlayerAction with 3002,4,1
08:15:05 <WARN:SceneScriptManager> trying to cancel a timer that's not active 133003002 delay1
08:24:37 <WARN:SceneScriptManager> trying to cancel a timer that's not active 133003439 born
08:25:08 <ERROR:EntityController> [LUA] call function failed in gadget 70380002 with OnBeHurt 1 0,true
org.luaj.vm2.LuaError: script:7 vm error: java.lang.NullPointerException
stack traceback:
        script:7: in function <script:1>
        [Java]: in ?
        at org.luaj.vm2.lib.jse.JavaMethod.invokeMethod(Unknown Source)
        at org.luaj.vm2.lib.jse.JavaMethod.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
        at org.luaj.vm2.LuaValue.invoke(Unknown Source)
        at emu.grasscutter.scripts.data.controller.EntityController.callControllerScriptFunc(EntityController.java:85)
        at emu.grasscutter.scripts.data.controller.EntityController.onBeHurt(EntityController.java:23)
        at emu.grasscutter.game.entity.GameEntity.runLuaCallbacks(GameEntity.java:242)
        at emu.grasscutter.game.entity.EntityBaseGadget.runLuaCallbacks(EntityBaseGadget.java:61)
        at emu.grasscutter.game.entity.GameEntity.damage(GameEntity.java:211)
        at emu.grasscutter.game.world.Scene.handleAttack(Scene.java:493)
        at emu.grasscutter.server.packet.recv.HandlerUnionCmdNotify.handle(HandlerUnionCmdNotify.java:39)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:82)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:227)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220)
        at java.base/java.util.Optional.of(Optional.java:113)
        at emu.grasscutter.scripts.ScriptLib.getSceneScriptManager(ScriptLib.java:57)
        at emu.grasscutter.scripts.ScriptLib.KillEntityByConfigId(ScriptLib.java:1131)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        ... 22 common frames omitted
08:27:39 <WARN:ScriptLib> [LUA] Call unchecked SetGroupReplaceable with 133003136 true

**Comment by NotThorny** [comment]
These are normal LUA errors, and do not affect your ability to play. You will see many of these while playing on Grasscutter.
Also, this is output from a [Grasscutter](https://github.com/Grasscutters/Grasscutter) cmd, and should be taken to [Grasscutter](https://github.com/Grasscutters/Grasscutter) issues for further assistance, as this is not an issue with Cultivation.

**Comment by LengXudong** [comment]
I appreciate your support and guidance. Thank you!
