### ISSUE TITLE
throw exception when start server

### ISSUE THREAD

**Issue by vali16** [Grasscutters/Cultivation#234]
```
19:23:30 <INFO:Grasscutter> Loading Grasscutter...
19:23:30 <INFO:Grasscutter> 正在启动 Grasscutter...
19:23:30 <INFO:Grasscutter> 游戏版本：5.0.0
19:23:30 <INFO:Grasscutter> Grasscutter 版本：1.7.5-dev-d11e13a
19:23:31 <WARN:HttpServer> [Dispatch] 未找到 SSL 证书！已回滚到 HTTP 模式
19:23:31 <INFO:ResourceLoader> 正在加载 resources...
19:23:32 <WARN:HttpServer> [Dispatch] 无法连接路由
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 14457059026087496718 at line 9 column 42 path $.preloadLuaList[0]
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:320)
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:310)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:929)
        at emu.grasscutter.utils.JsonUtils.loadToClass(JsonUtils.java:53)
        at emu.grasscutter.utils.JsonUtils.loadToClass(JsonUtils.java:67)
        at emu.grasscutter.data.ResourceLoader.lambda$loadQuests$35(ResourceLoader.java:559)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at emu.grasscutter.data.ResourceLoader.loadQuests(ResourceLoader.java:556)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:101)
        at emu.grasscutter.utils.lang.Language.loadTextMaps(Language.java:369)
        at emu.grasscutter.utils.lang.Language.loadTextMaps(Language.java:322)
        at emu.grasscutter.utils.lang.Language.getTextMapKey(Language.java:312)
        at emu.grasscutter.utils.lang.Language.getTextMapKey(Language.java:317)
        at emu.grasscutter.tools.Tools.createGachaMappingJsons(Tools.java:218)
        at emu.grasscutter.server.http.documentation.GachaMappingRequestHandler.<init>(GachaMappingRequestHandler.java:14)
        at emu.grasscutter.server.http.documentation.DocumentationServerHandler.applyRoutes(DocumentationServerHandler.java:11)
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:146)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:152)
Caused by: java.lang.NumberFormatException: Expected a long but was 14457059026087496718 at line 9 column 42 path $.preloadLuaList[0]
        at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:967)
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:318)
        ... 24 common frames omitted
19:23:32 <INFO:ResourceLoader> 正在加载 resources...
Exception in thread "main" java.lang.Exception: Script loader already initialized
        at emu.grasscutter.scripts.ScriptLoader.init(ScriptLoader.java:45)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:87)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:168)
```

**gracesscutter:**
grasscutter-1.7.5-dev.jar
**resources:**
https://gitlab.com/YuukiPS/GC-Resources/-/archive/5.0/GC-Resources-5.0.zip
**java:**
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

**Comment by NotThorny** [comment]
This is an issue with the server software or resources you are trying to use, and is not related to Cultivation. You should remake this issue in the correct project page.
